#!/bin/bash

# Task library

export DISPLAY_NAME="Charlie Gaffer"
export WEB_HOST_NAME="charliemoukbel.com"
export PRINT_VARS="$(PRINT_VARS) | BFF_URL"

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0

# This project

export GOOGLE_RECAPTCHA_SITE_KEY="6LeQMAsUAAAAAAm_KMxWOIpbdt3Lzung3U0Jaseh"
export MIXPANEL_TOKEN="787814775404613a99d581cb5093dc59"

BFF_URL_LOCAL="http://localhost:$(port charlie-gaffer-backend)"
BFF_URL_PROD="https://xeh4kq3z2i7sblpmw7qr55khcm0jxrjw.lambda-url.ap-southeast-2.on.aws"
export_staged BFF_URL
