#!/bin/bash

# Task library

export DISPLAY_NAME="Charlie Gaffer"
export WEB_HOST_NAME="charliemoukbel.com"

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0

# This project

export GOOGLE_RECAPTCHA_SITE_KEY="6LeQMAsUAAAAAAm_KMxWOIpbdt3Lzung3U0Jaseh"
export MIXPANEL_TOKEN="787814775404613a99d581cb5093dc59"
export BFF_URL="http://localhost:3000"

case $STAGE in
  local)
    export BFF_URL="http://localhost:3000"
    ;;
  test)
    export BFF_URL=""
    ;;
  prod)
    export BFF_URL="https://xeh4kq3z2i7sblpmw7qr55khcm0jxrjw.lambda-url.ap-southeast-2.on.aws"
    ;;    
esac
