#!/bin/bash

# Task library

export DISPLAY_NAME="Charlie Melbourne Gaffer"
export WEB_HOST_NAME="charliemoukbel.com"
export TEST_RUNNER="tape"

read -r -d '' INDEX_HTML_HEAD<<EOF
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
EOF

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0

# This project

CONTACT_URL_TEST="https://dvyxxovnfx7szz4ojnchxmww5q0fnvto.lambda-url.ap-southeast-2.on.aws/"
CONTACT_URL_PROD="https://74h46gbjouvnintgvgezfqzwma0yxtep.lambda-url.ap-southeast-2.on.aws/"

export STAGE=${STAGE:="test"}
[[ $STAGE = "prod" ]] && CONTACT_URL="${CONTACT_URL_PROD}"
export CONTACT_URL=${CONTACT_URL:=$CONTACT_URL_TEST}
export GOOGLE_RECAPTCHA_SITE_KEY="6LeQMAsUAAAAAAm_KMxWOIpbdt3Lzung3U0Jaseh"
export GOOGLE_ANALYTICS_TRACKING_ID="UA-86847178-1"
