service: web

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  profile: charliemoukbel-deploy
  environment: 
    APP_DOMAIN: ${self:custom.env.APP_DOMAIN}
    HOSTED_ZONE: ${self:custom.env.HOSTED_ZONE}

package:
  exclude:
    - secrets.yml

custom:
  stage: ${opt:stage, self:provider.stage}
  env: ${file(env.yml):${self:custom.stage}}    
  secrets: ${file(secrets.yml):${self:custom.stage}}    

resources:
  Resources:

    RootBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dev.charliemoukbel.com
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    RootBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: RootBucket
        PolicyDocument:
          Statement:
            Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject  
            Resource: 
              'Fn::Join':
                - ''
                - 
                  - 'arn:aws:s3:::'
                  - Ref: RootBucket
                  - /*

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultRootObject: index.html
          Origins:
            - DomainName:
                'Fn::GetAtt':
                  - RootBucket
                  - DomainName            
              Id: S3Origin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: match-viewer
          Aliases: 
            - dev.charliemoukbel.com
          DefaultCacheBehavior: 
            Compress: true
            DefaultTTL: 86400
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: allow-all
            ForwardedValues:
              QueryString: true

    CloudFrontDns:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: charliemoukbel.com.
        Name: dev.charliemoukbel.com.
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: 
            'Fn::GetAtt': 
              - CloudFrontDistribution
              - DomainName