service: web

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  profile: charliemoukbel-deploy

package:
  exclude:
    - secrets.yml

custom:
  stage: ${opt:stage, self:provider.stage}
  env: ${file(env.yml):${self:custom.stage}}    
  secrets: ${file(secrets.yml):${self:custom.stage}}    

resources:
  Resources:

    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.env.DOMAIN_NAME}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: RootBucket
        PolicyDocument:
          Statement:
            Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject  
            Resource: 
              'Fn::Join':
                - ''
                - 
                  - 'Fn::GetAtt':
                      - WebsiteBucket
                      - Arn
                  - /*

    WebsiteDNS:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: ${self:custom.env.HOSTED_ZONE}
        Name: ${self:custom.env.DOMAIN_NAME}
        Type: A
        AliasTarget:
          HostedZoneId: Z1WCIGYICN2BYD
          DNSName: 
            'Fn::GetAtt': 
              - WebsiteBucket
              - DomainName

    WWWDNS:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: ${self:custom.env.HOSTED_ZONE}
        Name: www.${self:custom.env.DOMAIN_NAME}
        Type: A
        AliasTarget:
          HostedZoneId: Z1WCIGYICN2BYD
          DNSName: 
            'Fn::GetAtt': 
              - WebsiteBucket
              - DomainName            