#!/bin/bash

export PROJECT_NAME="Charlie Moukbel - Gaffer"
export WEB_HOST_NAME="charliemoukbel.com"

export ESLINT_PATHS=("$SRC")

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0

# Project specific

export STAGE=${STAGE:="test"}

export AWS_PROFILE="charliemoukbel"
export AWS_REGION="ap-southeast-2"
export AWS_SES_REGION="ap-southeast-2"
export AWS_SES_IDENTITY="$WEB_HOST_NAME"
export MESSAGES_TABLE_NAME="messages-$STAGE"
export GOOGLE_RECAPTCHA_VERIFY_URL="https://www.google.com/recaptcha/api/siteverify"
export GOOGLE_RECAPTCHA_SITE_KEY="6LeQMAsUAAAAAAm_KMxWOIpbdt3Lzung3U0Jaseh"
export GOOGLE_RECAPTCHA_SECRET_KEY=$(aws ssm get-parameter --region $AWS_REGION --name google_recaptcha_secret_key --with-decryption | jq -r '.Parameter.Value')

export PRIMARY_CONTACT_EMAIL="Charlie Moukbel <cmoukbel@hotmail.com>"
export TECHNICAL_CONTACT_EMAIL="Matt Riley <mattrileyaus@gmail.com>"
export NOREPLY_EMAIL="Gaffer website <noreply@$WEB_HOST_NAME>"
