#!/bin/bash

. ../task-vars-common

# Task library

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0

# This project

function secret {
    echo $(aws ssm get-parameter --region $AWS_REGION --name $1 --with-decryption | jq -r '.Parameter.Value')
}

export AWS_PROFILE="charlie-gaffer"
export AWS_REGION="ap-southeast-2"
export AWS_SES_REGION="$AWS_REGION"
export AWS_SES_IDENTITY="$WEB_HOST_NAME"
export MESSAGES_TABLE_NAME="messages"
export GOOGLE_RECAPTCHA_VERIFY_URL="https://www.google.com/recaptcha/api/siteverify"
export GOOGLE_RECAPTCHA_SECRET_KEY=$(secret google_recaptcha_secret_key)
export PRIMARY_CONTACT_EMAIL=$(secret primary_contact_email)
export TECHNICAL_CONTACT_EMAIL=$(secret technical_contact_email)
export NOREPLY_EMAIL="Gaffer website <noreply@$WEB_HOST_NAME>"
