service: charliemoukbel

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  profile: charliemoukbel-deploy
  tracing: true
  environment: 
    MESSAGES_TABLE_NAME: "messages-${self:provider.stage}"
    AWS_REGION_SES: "${self:custom.env.AWS_REGION_SES}"
    NOTIFICATION_FROM_ADDRESS: "${self:custom.env.NOTIFICATION_FROM_ADDRESS}"
    NOTIFICATION_TO_ADDRESS: "${self:custom.env.NOTIFICATION_TO_ADDRESS}"
    GOOGLE_RECAPTCHA_SECRET_KEY: "${self:custom.secrets.GOOGLE_RECAPTCHA_SECRET_KEY}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - 'Fn::Join':
            - ':'
            -
              - arn:aws:dynamodb
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - table/messages-${self:provider.stage}
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: 
        - 'Fn::Join':
            - ':'
            -
              - arn:aws:ses
              - ${self:custom.env.AWS_REGION_SES}
              - Ref: AWS::AccountId
              - '*'

package:
  exclude:
    - secrets.yml

custom:
  stage: ${opt:stage, self:provider.stage}
  env: ${file(env.yml):${self:custom.stage}}    
  secrets: ${file(secrets.yml):${self:custom.stage}}    

functions:
  sendMessage:
    handler: handler.send
    events:
      - http:
          path: messages
          method: post
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
          